name: roxbury plains
favicon: null
layout_spectrum: 0.8447048040106893
typography_spectrum: 0.9974468748550862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.012905003502964973
  lightness: 0.7474185971077532
  saturation: 0.733833315083757
  rhythmicContrast: 0.08268802496604621
purpose: []
